general {
    lock_cmd = hyprlock
    unlock_cmd = notify-send "unlock!" 
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 180
    on-timeout = gdbus call -e -d net.zoidplex.wlr_gamma_service -o /net/zoidplex/wlr_gamma_service -m net.zoidplex.wlr_gamma_service.brightness.set 0.2          # brightness decrease after some time

    on-resume = gdbus call -e -d net.zoidplex.wlr_gamma_service -o /net/zoidplex/wlr_gamma_service -m net.zoidplex.wlr_gamma_service.brightness.set 0.4          # brightness increased after reactivvity              
}

listener {
    timeout = 
}

listener {
    timeout = 240
    on-timeout = hyprctl dispatch dpms off        # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on          # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 300
    on-timeout =hyprlock
}
