general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances
    unlock_cmd = notify-send "unlock!" 
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

# 1. Dim the screen
listener {
    timeout = 60
    # Save current brightness, then set it to 1/4 of its current value
    on-timeout = sh -c 'brightnessctl -s set $(( $(brightnessctl get) / 4 ))'
    # Restore the previously saved brightness level
    on-resume = brightnessctl -r
}

# 2. Lock the screen
listener {
    timeout = 120
    on-timeout = loginctl lock-session          # triggers the lock_cmd in the general section
}

# 3. Turn off the display
listener {
    timeout = 180
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
